### ISSUE TITLE
BBB 2.4 

### ISSUE THREAD

**Issue by justvanbloom** [aau-zid/BigBlueButton-liveStreaming#139]
https://github.com/aau-zid/BigBlueButton-liveStreaming/blob/0f6be59a03b00130a1ff4b7b2cb5a978248ba223/stream.py#L190

In BBB 2.4 container ist removed. 

BUG: 
INFO:root:Waiting for chat input window to appear.
Traceback (most recent call last):
  File "stream.py", line 262, in <module>
    bbb_browser()
  File "stream.py", line 190, in bbb_browser
    browser.execute_script("document.getElementById('container').setAttribute('style','margin-bottom:30px');")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'setAttribute' of null
  (Session info: chrome=91.0.4472.77)

FIX:

document.getElementById('app').setAttribute('style','margin-bottom:30px');

Can you make one version with this so i can pull it from dockerhub? would be awsome.

**Comment by justvanbloom** [comment]
Can confirm. BBB 2.4 wirh change above works. 
Changed it and build it local.

**Comment by on8pz** [comment]
I created PR #142 for fixing this

**Comment by Marzal** [comment]
I think this issue could now be closed with commit 400d79bc9c338662c54f8d79a41ebc6cc23df7bc. PR #142 was merged
