### ISSUE TITLE
Browser Crashed

### ISSUE THREAD

**Issue by shah-manthan9** [aau-zid/BigBlueButton-liveStreaming#4]
Hi Man,
I finally got it how to get the meeting id and callbacks but once it is started it always gives this error and crashes
```

liveStreaming   | INFO:root:Starting browser!!
liveStreaming   | INFO:root:Open BBB and hide elements!!
liveStreaming   | Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 94, in <module>
liveStreaming   |     bbb_browser()
liveStreaming   |   File "stream.py", line 63, in bbb_browser
liveStreaming   |     browser.find_elements_by_css_selector('[aria-label="Listen only"]')[0].click()
liveStreaming   |   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
liveStreaming   |     self._execute(Command.CLICK_ELEMENT)
liveStreaming   |   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
liveStreaming   |     return self._parent.execute(command, params)
liveStreaming   |   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
liveStreaming   |     self.error_handler.check_response(response)
liveStreaming   |   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
liveStreaming   |     raise exception_class(message, screen, stacktrace)
liveStreaming   | selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
liveStreaming   | from unknown error: cannot determine loading status
liveStreaming   | from tab crashed
liveStreaming   |   (Session info: chrome=81.0.4044.129)

```

**Comment by mtsonline** [comment]
Hi,

we added
shm-size=1gb

could you please test, if it works for you now?

**Comment by shah-manthan9** [comment]
It is working now but there is no sound...

**Comment by mtsonline** [comment]
ok, great, that it starts eventually.

If you join the same room with your browser, do you hear something?
Is video working?
How do you play the stream?

**Comment by shah-manthan9** [comment]
When I join the room I can Hear BBB assistant voice. Also, when I joined from other browser I can hear myself. 
Video is working fine, there is some lag sometime but works fine
I am streaming it on youtube.

**Comment by shah-manthan9** [comment]
Just Noticed that Live user do not have listen only icon. Can that be the issue?

**Comment by shah-manthan9** [comment]
Also got error on video codec on youtube live stream studio 

```
Error
The video is encoded with an unsupported codec. Please set the video codec for the stream to a supported codec (H.264).

```

**Comment by mikosche** [comment]
Can you send us a test meeting?
It sounds like the click event for 'Listen only' don't work.

**Comment by shah-manthan9** [comment]
I currently live you can join on 
https://shadowwalker.tech/b/man-kdw-k2c

Also ffmpeg error on console
This is Main Error
```
 Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
liveStreaming   | Codec AVOption preset (Configuration preset) specified for output file #0 (rtmp://a.rtmp.youtube.com/live2/d9cz-b7ew-35k1-dcaj) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.

```

This Error comes sometimes
```
 Input #0, x11grab, from ':122':
liveStreaming   |   Duration: N/A, start: 1589036095.689192, bitrate: N/A
liveStreaming   |     Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 24 fps, 1000k tbr, 1000k tbn, 1000k tbc
liveStreaming   | ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

```

**Comment by karthikindia** [comment]
can you help me on this

**Comment by PasqualeAiello** [comment]
> rtmp://a.rtmp.youtube.com/live2/d9cz-b7ew-35k1-dcaj

Add /stream/  before key and try
