### ISSUE TITLE
HTTP Error 403 when starting livestream container

### ISSUE THREAD

**Issue by canhdh2** [aau-zid/BigBlueButton-liveStreaming#80]
Hi guys!
I have configured env variable in docker-compose.yml and start livestream container by `docker-compose up -d`, and I received this error:
```
INFO:root:Starting browser!!
INFO:root:Open BBB and hide elements!!
INFO:root:create_meeting...
Traceback (most recent call last):
  File "stream.py", line 167, in <module>
    bbb_browser()
  File "stream.py", line 69, in bbb_browser
    create_meeting()
  File "stream.py", line 105, in create_meeting
    return bbb.create_meeting(args.id, params=create_params)
  File "/usr/local/lib/python3.6/dist-packages/bigbluebutton_api_python/bigbluebutton.py", line 47, in create_meeting
    response = self.__send_api_request(ApiMethod.CREATE, params)
  File "/usr/local/lib/python3.6/dist-packages/bigbluebutton_api_python/bigbluebutton.py", line 135, in __send_api_request
    response = urlopen(url).read()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

This is my docker-compose.yml:
```yaml
version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://bbb.my-domain.com/bigbluebutton/api/
      # BigBlueButton secret:
      - BBB_SECRET=my-secret
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=test-livestream-11234
      # start meeting (optional):
      - BBB_START_MEETING=true
      # attendee password (optional - has to be set to the attendee password of moodle/greenlight or any other frontend$
      - BBB_ATTENDEE_PASSWORD=ap
      # moderator password (optional - has to be set to the moderator password of moodle/greenlight or any other fronte$
      - BBB_MODERATOR_PASSWORD=mp
      # meeting title (optional):
      - BBB_MEETING_TITLE=liveStreaming
      # download / save BigBlueButton meeting
      - BBB_DOWNLOAD_MEETING=false
      # play intro file (can be a local file in videodata folder e.g. /video/intro.mp4 or a url of a mediastream e.g. h$
      #- BBB_INTRO=false
      # begin the intro at position (optional, e.g. 00:00:05)
      - BBB_BEGIN_INTRO_AT=04:40
      # end intro after (optional, e.g. 01:00:00 - after one hour)
      - BBB_END_INTRO_AT=
      # Media server url:
      - BBB_STREAM_URL=rtmp://my-rtmp-server/live/my-stream-key
      # Timezone (default: Europe/Vienna):
      - TZ=Asia/Saigon

    volumes:
      - ./videodata:/video
```

I have tested create api with API Mate and it's work. I dont know why this appears, how can i fix it?
Thanks a lot!

**Comment by mtsonline** [comment]
Hi,

can you comment the download parameter, instead of setting it to false?
and please check if the bbb server can be reached from your host where you start liveStreaming.

at first sight I do not see any other settings that could be an issue.
